/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misiontic.reflix.redlix.vista;

import java.awt.CardLayout;
import java.awt.Color;
import java.sql.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import misiontic.reflix.redlix.modelos.Contenido;
import misiontic.reflix.redlix.RedlixApplication;
import misiontic.reflix.redlix.SpringContext;
import misiontic.reflix.redlix.modelos.Director;
import misiontic.reflix.redlix.modelos.Pelicula;
import misiontic.reflix.redlix.modelos.Serie;
import misiontic.reflix.redlix.modelos.Usuario;
import misiontic.reflix.redlix.repositorios.ContenidoRepositorio;
import misiontic.reflix.redlix.repositorios.DirectorRepositorio;
import misiontic.reflix.redlix.repositorios.PeliculaRepositorio;
import misiontic.reflix.redlix.repositorios.SerieRepositorio;
import misiontic.reflix.redlix.repositorios.UsuarioRepositorio;
import org.springframework.beans.factory.annotation.Autowired;

/**
 *
 * @author Danie
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    ContenidoRepositorio contenidoRepositorio;
    DirectorRepositorio directorRepositorio;
    PeliculaRepositorio peliculaRepositorio;
    SerieRepositorio serieRepositorio;
    UsuarioRepositorio usuarioRepositorio;

    CardLayout cardLayout;
    private List<Contenido> contenidos;
    private List<Director> directores;
    private List<Pelicula> peliculas;
    private List<Serie> series;
    private List<Usuario> usuarios;
    
    int xx,yy;

    public Home() {
        initComponents();
        cardLayout = (CardLayout) (pnlCards.getLayout());

        String[] args = {};
        RedlixApplication.runSpringServer(args);

        contenidoRepositorio = SpringContext.getBean(ContenidoRepositorio.class);
        directorRepositorio = SpringContext.getBean(DirectorRepositorio.class);
        peliculaRepositorio = SpringContext.getBean(PeliculaRepositorio.class);
        serieRepositorio = SpringContext.getBean(SerieRepositorio.class);
        usuarioRepositorio = SpringContext.getBean(UsuarioRepositorio.class);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        sidepanel = new javax.swing.JPanel();
        btn_contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ind_contenidos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_peliculas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ind_peliculas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_series = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ind_series = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_usuarios = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ind_usuarios = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_directores = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ind_directores = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnlCard1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_contenido = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        pnlCard2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_peliculas = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        del_peliculas = new javax.swing.JButton();
        pnlCard3 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_series = new javax.swing.JTable();
        del_serie = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        pnlCard4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_usuarios = new javax.swing.JTable();
        del_usuario = new javax.swing.JButton();
        editusuario = new javax.swing.JButton();
        crearUsuarioBtn = new javax.swing.JButton();
        pnlCard5 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tbl_directores = new javax.swing.JTable();
        del_director = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pnlParent.setBackground(new java.awt.Color(0, 0, 0));
        pnlParent.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setForeground(new java.awt.Color(45, 45, 45));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });
        jPanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel1MousePressed(evt);
            }
        });

        jLabel13.setBackground(new java.awt.Color(51, 51, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1092, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(450, 600));

        sidepanel.setBackground(new java.awt.Color(51, 51, 51));
        sidepanel.setForeground(new java.awt.Color(0, 0, 0));
        sidepanel.setPreferredSize(new java.awt.Dimension(200, 622));

        btn_contenido.setBackground(new java.awt.Color(51, 51, 51));
        btn_contenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_contenidoMousePressed(evt);
            }
        });
        btn_contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_contenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_contenidos.setBackground(new java.awt.Color(255, 51, 0));
        ind_contenidos.setOpaque(false);

        javax.swing.GroupLayout ind_contenidosLayout = new javax.swing.GroupLayout(ind_contenidos);
        ind_contenidos.setLayout(ind_contenidosLayout);
        ind_contenidosLayout.setHorizontalGroup(
            ind_contenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_contenidosLayout.setVerticalGroup(
            ind_contenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_contenido.add(ind_contenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Contenidos");
        btn_contenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("REDFLIX");

        btn_peliculas.setBackground(new java.awt.Color(51, 51, 51));
        btn_peliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_peliculasMousePressed(evt);
            }
        });
        btn_peliculas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_peliculas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_peliculas.setBackground(new java.awt.Color(255, 51, 0));
        ind_peliculas.setOpaque(false);

        javax.swing.GroupLayout ind_peliculasLayout = new javax.swing.GroupLayout(ind_peliculas);
        ind_peliculas.setLayout(ind_peliculasLayout);
        ind_peliculasLayout.setHorizontalGroup(
            ind_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_peliculasLayout.setVerticalGroup(
            ind_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_peliculas.add(ind_peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Peliculas");
        btn_peliculas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        btn_series.setBackground(new java.awt.Color(51, 51, 51));
        btn_series.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_seriesMousePressed(evt);
            }
        });
        btn_series.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_series.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_series.setBackground(new java.awt.Color(255, 51, 0));
        ind_series.setOpaque(false);

        javax.swing.GroupLayout ind_seriesLayout = new javax.swing.GroupLayout(ind_series);
        ind_series.setLayout(ind_seriesLayout);
        ind_seriesLayout.setHorizontalGroup(
            ind_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_seriesLayout.setVerticalGroup(
            ind_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_series.add(ind_series, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Series");
        btn_series.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 40));

        btn_usuarios.setBackground(new java.awt.Color(51, 51, 51));
        btn_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_usuariosMousePressed(evt);
            }
        });
        btn_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_usuarios.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_usuarios.setBackground(new java.awt.Color(255, 51, 0));
        ind_usuarios.setOpaque(false);

        javax.swing.GroupLayout ind_usuariosLayout = new javax.swing.GroupLayout(ind_usuarios);
        ind_usuarios.setLayout(ind_usuariosLayout);
        ind_usuariosLayout.setHorizontalGroup(
            ind_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_usuariosLayout.setVerticalGroup(
            ind_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_usuarios.add(ind_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuarios");
        btn_usuarios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, -1, 40));

        btn_directores.setBackground(new java.awt.Color(51, 51, 51));
        btn_directores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_directoresMousePressed(evt);
            }
        });
        btn_directores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_directores.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_directores.setBackground(new java.awt.Color(255, 51, 0));
        ind_directores.setOpaque(false);

        javax.swing.GroupLayout ind_directoresLayout = new javax.swing.GroupLayout(ind_directores);
        ind_directores.setLayout(ind_directoresLayout);
        ind_directoresLayout.setHorizontalGroup(
            ind_directoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_directoresLayout.setVerticalGroup(
            ind_directoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_directores.add(ind_directores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Directores");
        btn_directores.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel12.setText("V1.0");

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
            .addComponent(btn_series, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_directores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_peliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(29, 29, 29))))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                .addGap(95, 95, 95)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addComponent(btn_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_series, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_directores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(174, 174, 174))
        );

        jSplitPane1.setLeftComponent(sidepanel);

        pnlCards.setBackground(new java.awt.Color(204, 204, 204));
        pnlCards.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 931, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 622, Short.MAX_VALUE)
        );

        pnlCards.add(jPanel2, "card7");

        pnlCard1.setBackground(new java.awt.Color(204, 204, 204));

        tbl_contenido.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Tipo", "Titulo"
            }
        ));
        jScrollPane1.setViewportView(tbl_contenido);

        jLabel14.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Contenido");

        javax.swing.GroupLayout pnlCard1Layout = new javax.swing.GroupLayout(pnlCard1);
        pnlCard1.setLayout(pnlCard1Layout);
        pnlCard1Layout.setHorizontalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        pnlCard1Layout.setVerticalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard1, "pnlCard1");

        pnlCard2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel15.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setText("Peliculas");

        tbl_peliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Titulo", "Resumen", "Año", "Director", "Contenido"
            }
        ));
        tbl_peliculas.setRowHeight(70);
        tbl_peliculas.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tbl_peliculas);

        jButton4.setText("Crear");

        jButton5.setText("Editar");

        del_peliculas.setText("Eliminar");
        del_peliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                del_peliculasMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlCard2Layout = new javax.swing.GroupLayout(pnlCard2);
        pnlCard2.setLayout(pnlCard2Layout);
        pnlCard2Layout.setHorizontalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlCard2Layout.createSequentialGroup()
                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCard2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(del_peliculas))
                    .addGroup(pnlCard2Layout.createSequentialGroup()
                        .addGap(0, 50, Short.MAX_VALUE)
                        .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(39, 39, 39))
        );
        pnlCard2Layout.setVerticalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton5)
                    .addComponent(del_peliculas))
                .addGap(56, 56, 56))
        );

        pnlCards.add(pnlCard2, "pnlCard2");

        pnlCard3.setBackground(new java.awt.Color(204, 204, 204));

        jLabel16.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Series");

        tbl_series.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Titulo", "Temporadas", "Episodios", "idContenido"
            }
        ));
        tbl_series.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(tbl_series);

        del_serie.setText("Eliminar");
        del_serie.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                del_serieMousePressed(evt);
            }
        });

        jButton10.setText("Editar");

        jButton11.setText("Crear");

        javax.swing.GroupLayout pnlCard3Layout = new javax.swing.GroupLayout(pnlCard3);
        pnlCard3.setLayout(pnlCard3Layout);
        pnlCard3Layout.setHorizontalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCard3Layout.createSequentialGroup()
                        .addComponent(jButton11)
                        .addGap(18, 18, 18)
                        .addComponent(jButton10)
                        .addGap(18, 18, 18)
                        .addComponent(del_serie))
                    .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlCard3Layout.setVerticalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard3Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del_serie)
                    .addComponent(jButton10)
                    .addComponent(jButton11))
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard3, "pnlCard3");

        pnlCard4.setBackground(new java.awt.Color(204, 204, 204));

        jLabel17.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Usuarios");

        tbl_usuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Alias", "Nombre", "Apellido", "Email", "Celular", "Contraseña", "Fecha de Nacimiento"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_usuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(tbl_usuarios);

        del_usuario.setText("Eliminar");
        del_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                del_usuarioMousePressed(evt);
            }
        });

        editusuario.setText("Editar");
        editusuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                editusuarioMousePressed(evt);
            }
        });

        crearUsuarioBtn.setText("Crear");
        crearUsuarioBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                crearUsuarioBtnMousePressed(evt);
            }
        });

        javax.swing.GroupLayout pnlCard4Layout = new javax.swing.GroupLayout(pnlCard4);
        pnlCard4.setLayout(pnlCard4Layout);
        pnlCard4Layout.setHorizontalGroup(
            pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard4Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCard4Layout.createSequentialGroup()
                        .addComponent(crearUsuarioBtn)
                        .addGap(18, 18, 18)
                        .addComponent(editusuario)
                        .addGap(18, 18, 18)
                        .addComponent(del_usuario))
                    .addGroup(pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 842, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        pnlCard4Layout.setVerticalGroup(
            pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard4Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(del_usuario)
                    .addComponent(editusuario)
                    .addComponent(crearUsuarioBtn))
                .addContainerGap(67, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard4, "pnlCard4");

        pnlCard5.setBackground(new java.awt.Color(204, 204, 204));

        jLabel18.setFont(new java.awt.Font("Century Gothic", 1, 48)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Directores");

        jScrollPane5.setBackground(new java.awt.Color(204, 204, 204));
        jScrollPane5.setForeground(new java.awt.Color(204, 204, 204));

        tbl_directores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nombre", "Apellido", "Nacionalidad"
            }
        ));
        tbl_directores.setOpaque(false);
        jScrollPane5.setViewportView(tbl_directores);

        del_director.setText("Eliminar");
        del_director.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                del_directorMousePressed(evt);
            }
        });

        jButton13.setText("Editar");

        jButton14.setText("Crear");

        javax.swing.GroupLayout pnlCard5Layout = new javax.swing.GroupLayout(pnlCard5);
        pnlCard5.setLayout(pnlCard5Layout);
        pnlCard5Layout.setHorizontalGroup(
            pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard5Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlCard5Layout.createSequentialGroup()
                        .addComponent(jButton14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(del_director)
                        .addGap(6, 6, 6))
                    .addGroup(pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        pnlCard5Layout.setVerticalGroup(
            pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard5Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton13)
                    .addComponent(jButton14)
                    .addComponent(del_director))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard5, "pnlCard5");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout pnlParentLayout = new javax.swing.GroupLayout(pnlParent);
        pnlParent.setLayout(pnlParentLayout);
        pnlParentLayout.setHorizontalGroup(
            pnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1133, Short.MAX_VALUE)
            .addGroup(pnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlParentLayout.setVerticalGroup(
            pnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParentLayout.createSequentialGroup()
                .addGap(0, 44, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 624, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlParentLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 610, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlParent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_contenidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_contenidoMousePressed
        setColor(btn_contenido);
        resetColor(btn_directores);
        resetColor(btn_peliculas);
        resetColor(btn_series);
        resetColor(btn_usuarios);
        ind_contenidos.setOpaque(true);
        ind_directores.setOpaque(false);
        ind_peliculas.setOpaque(false);
        ind_series.setOpaque(false);
        ind_usuarios.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard1");
        actualizarLista("contenido");

    }//GEN-LAST:event_btn_contenidoMousePressed

    private void btn_peliculasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peliculasMousePressed
        setColor(btn_peliculas);
        resetColor(btn_directores);
        resetColor(btn_contenido);
        resetColor(btn_series);
        resetColor(btn_usuarios);
        ind_peliculas.setOpaque(true);
        ind_contenidos.setOpaque(false);
        ind_directores.setOpaque(false);
        ind_series.setOpaque(false);
        ind_usuarios.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard2");
        actualizarLista("pelicula");
    }//GEN-LAST:event_btn_peliculasMousePressed

    private void btn_seriesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seriesMousePressed
        setColor(btn_series);
        resetColor(btn_directores);
        resetColor(btn_contenido);
        resetColor(btn_peliculas);
        resetColor(btn_usuarios);
        ind_series.setOpaque(true);
        ind_contenidos.setOpaque(false);
        ind_directores.setOpaque(false);
        ind_peliculas.setOpaque(false);
        ind_usuarios.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard3");
        actualizarLista("serie");
    }//GEN-LAST:event_btn_seriesMousePressed

    private void btn_usuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMousePressed
        setColor(btn_usuarios);
        resetColor(btn_directores);
        resetColor(btn_contenido);
        resetColor(btn_peliculas);
        resetColor(btn_series);
        ind_usuarios.setOpaque(true);
        ind_contenidos.setOpaque(false);
        ind_directores.setOpaque(false);
        ind_peliculas.setOpaque(false);
        ind_series.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard4");
        actualizarLista("usuario");
    }//GEN-LAST:event_btn_usuariosMousePressed

    private void btn_directoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_directoresMousePressed
        setColor(btn_directores);
        resetColor(btn_usuarios);
        resetColor(btn_contenido);
        resetColor(btn_peliculas);
        resetColor(btn_series);
        ind_directores.setOpaque(true);
        ind_contenidos.setOpaque(false);
        ind_peliculas.setOpaque(false);
        ind_series.setOpaque(false);
        ind_usuarios.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard5");
        actualizarLista("director");
    }//GEN-LAST:event_btn_directoresMousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel13MousePressed

    private void del_peliculasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_peliculasMousePressed
        eliminar("pelicula");
    }//GEN-LAST:event_del_peliculasMousePressed

    private void del_serieMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_serieMousePressed
        eliminar("serie");
    }//GEN-LAST:event_del_serieMousePressed

    private void del_usuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_usuarioMousePressed
        eliminar("usuario");
    }//GEN-LAST:event_del_usuarioMousePressed

    private void del_directorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_del_directorMousePressed
        eliminar("director");
    }//GEN-LAST:event_del_directorMousePressed

    private void crearUsuarioBtnMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_crearUsuarioBtnMousePressed
        
        UsuarioForm usrFrom = new UsuarioForm(true, null);
        usrFrom.setVisible(true);
         actualizarLista("usuario");
    }//GEN-LAST:event_crearUsuarioBtnMousePressed

    private void editusuarioMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editusuarioMousePressed
        UsuarioForm usrFrom = new UsuarioForm(false, getRowUsr());
        usrFrom.setVisible(true);
        actualizarLista("usuario");
    }//GEN-LAST:event_editusuarioMousePressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - yy);
    }//GEN-LAST:event_jPanel1MouseDragged

    private void jPanel1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MousePressed
        xx = evt.getX();
        yy = evt.getY();
    }//GEN-LAST:event_jPanel1MousePressed

    Usuario getRowUsr(){
        Usuario usr = new Usuario();
        usr.setAlias( (String) tbl_usuarios.getModel().getValueAt(tbl_usuarios.getSelectedRow(), 0) );
        usr.setNombre((String) tbl_usuarios.getModel().getValueAt(tbl_usuarios.getSelectedRow(), 1));
        usr.setApellido((String) tbl_usuarios.getModel().getValueAt(tbl_usuarios.getSelectedRow(), 2));
        usr.setEmail((String) tbl_usuarios.getModel().getValueAt(tbl_usuarios.getSelectedRow(), 3));
        usr.setCelular((String) tbl_usuarios.getModel().getValueAt(tbl_usuarios.getSelectedRow(), 4));
        usr.setContrasena((String) tbl_usuarios.getModel().getValueAt(tbl_usuarios.getSelectedRow(), 5));
        usr.setFechaNacimiento((Date) tbl_usuarios.getModel().getValueAt(tbl_usuarios.getSelectedRow(), 6));
    
        return usr;
    }
    void setColor(JPanel panel) {
        panel.setBackground(new Color(102, 102, 102));
    }

    void resetColor(JPanel panel) {
        panel.setBackground(new Color(51, 51, 51));
    }

    void actualizarLista(String tipo) {
        switch (tipo) {
            case "contenido":
                try {
                contenidos = contenidoRepositorio.findAll();
                DefaultTableModel modelo = (DefaultTableModel) tbl_contenido.getModel();
                int numCols = modelo.getColumnCount();
                tbl_contenido.getColumnModel().getColumn(0).setMinWidth(0);
                tbl_contenido.getColumnModel().getColumn(0).setMaxWidth(0);
                modelo.setRowCount(0);

                for (Contenido contenido : contenidos) {
                    Object[] fila = new Object[numCols];

                    fila[0] = contenido.getIdContenido();
                    fila[1] = contenido.getTipoContenido();
                    fila[2] = contenido.getTituloContenido();

                    modelo.addRow(fila);
                }

            } catch (Exception e) {

            }
            break;
            case "director":
                try {
                directores = directorRepositorio.findAll();
                DefaultTableModel modelo = (DefaultTableModel) tbl_directores.getModel();
                int numCols = modelo.getColumnCount();

                modelo.setRowCount(0);

                for (Director director : directores) {
                    Object[] fila = new Object[numCols];

                    fila[0] = director.getIdDirector();
                    fila[1] = director.getNombre();
                    fila[2] = director.getApellido();
                    fila[3] = director.getNacionalidad();

                    modelo.addRow(fila);
                }

            } catch (Exception e) {

            }

            break;
            case "pelicula":
                try {
                peliculas = peliculaRepositorio.findAll();
                DefaultTableModel modelo = (DefaultTableModel) tbl_peliculas.getModel();
                int numCols = modelo.getColumnCount();

                modelo.setRowCount(0);
                tbl_peliculas.setRowHeight(70);
                for (Pelicula pelicula : peliculas) {
                    Object[] fila = new Object[numCols];

                    fila[0] = pelicula.getIdPelicula();
                    fila[1] = pelicula.getTitulo();
                    fila[2] = pelicula.getResumen();
                    fila[3] = pelicula.getAnio();
                    fila[4] = pelicula.getIdDirector();
                    fila[5] = pelicula.getIdContenido();

                    modelo.addRow(fila);
                }

            } catch (Exception e) {

            }
            break;
            case "serie":
                try {
                series = serieRepositorio.findAll();
                DefaultTableModel modelo = (DefaultTableModel) tbl_series.getModel();
                int numCols = modelo.getColumnCount();

                modelo.setRowCount(0);

                for (Serie serie : series) {
                    Object[] fila = new Object[numCols];

                    fila[0] = serie.getIdSerie();
                    fila[1] = serie.getTitulo();
                    fila[2] = serie.getTemporadas();
                    fila[3] = serie.getEpidosdios();
                    fila[4] = serie.getIdContenido();

                    modelo.addRow(fila);
                }

            } catch (Exception e) {

            }
            break;
            case "usuario":
                try {
                usuarios = usuarioRepositorio.findAll();
                    System.out.println(usuarios);
                DefaultTableModel modelo = (DefaultTableModel) tbl_usuarios.getModel();
                int numCols = modelo.getColumnCount();

                modelo.setRowCount(0);

                for (Usuario usuario : usuarios) {
                    Object[] fila = new Object[numCols];

                    fila[0] = usuario.getAlias();
                    fila[1] = usuario.getNombre();
                    fila[2] = usuario.getApellido();
                    fila[3] = usuario.getEmail();
                    fila[4] = usuario.getCelular();
                    fila[5] = usuario.getContrasena();
                    fila[6] = usuario.getFechaNacimiento();

                    modelo.addRow(fila);
                }

            } catch (Exception e) {

            }
            break;

        }

    }

    void eliminar(String tipo) {
        int response = JOptionPane.showConfirmDialog(null, "Seguro que desea eliminar?", "Eliminar", JOptionPane.YES_NO_OPTION);
        switch (tipo) {
            case "director":
                if (response == JOptionPane.YES_OPTION) {
                    String directorId = String.valueOf(tbl_directores.getModel().getValueAt(tbl_directores.getSelectedRow(), 0));
                    System.out.println(directorId);
                }
                break;
            case "pelicula":
                if (response == JOptionPane.YES_OPTION) {
                    String peliculaId = (String) tbl_peliculas.getModel().getValueAt(tbl_peliculas.getSelectedRow(), 0);
                    System.out.println(peliculaId);
                }
                break;
            case "serie":
                if (response == JOptionPane.YES_OPTION) {
                    String serieId = (String) tbl_series.getModel().getValueAt(tbl_series.getSelectedRow(), 0);
                    System.out.println(serieId);
                }
                break;
            case "usuario":
                if (response == JOptionPane.YES_OPTION) {
                    usuarioRepositorio.delete(getRowUsr());
                    actualizarLista("usuario");
                }
                break;

        }

    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_contenido;
    private javax.swing.JPanel btn_directores;
    private javax.swing.JPanel btn_peliculas;
    private javax.swing.JPanel btn_series;
    private javax.swing.JPanel btn_usuarios;
    private javax.swing.JButton crearUsuarioBtn;
    private javax.swing.JButton del_director;
    private javax.swing.JButton del_peliculas;
    private javax.swing.JButton del_serie;
    private javax.swing.JButton del_usuario;
    private javax.swing.JButton editusuario;
    private javax.swing.JPanel ind_contenidos;
    private javax.swing.JPanel ind_directores;
    private javax.swing.JPanel ind_peliculas;
    private javax.swing.JPanel ind_series;
    private javax.swing.JPanel ind_usuarios;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JPanel pnlCard4;
    private javax.swing.JPanel pnlCard5;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel sidepanel;
    private javax.swing.JTable tbl_contenido;
    private javax.swing.JTable tbl_directores;
    private javax.swing.JTable tbl_peliculas;
    private javax.swing.JTable tbl_series;
    private javax.swing.JTable tbl_usuarios;
    // End of variables declaration//GEN-END:variables
}
