/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misiontic.reflix.redlix.vista;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import misiontic.reflix.redlix.RedlixApplication;
import misiontic.reflix.redlix.SpringContext;
import misiontic.reflix.redlix.modelos.Usuario;
import misiontic.reflix.redlix.repositorios.UsuarioRepositorio;

/**
 *
 * @author Danie
 */
public class UsuarioForm extends javax.swing.JDialog {

    boolean crear;
    Usuario usuario;
    UsuarioRepositorio usuarioRepositorio;

    /**
     * Creates new form UsuarioForm
     *
     * @param crear
     * @param usuario
     */
    public UsuarioForm(boolean crear, Usuario usuario) {
        initComponents();
        setModal(true);

        this.crear = crear;
        this.usuario = usuario;

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        aliasInfo.setVisible(false);
        nombreInfo.setVisible(false);
        apellidoInfo.setVisible(false);
        emailInfo.setVisible(false);
        celularInfo.setVisible(false);
        fechaInfo.setVisible(false);
        passwordInfo.setVisible(false);
        UsrFormInfo.setVisible(false);

        String[] args = {};
        RedlixApplication.runSpringServer(args);

        usuarioRepositorio = SpringContext.getBean(UsuarioRepositorio.class);

        if (!crear) {
            aliasUsr.setText(usuario.getAlias());
            nombreUsr.setText(usuario.getNombre());
            apellidoUsr.setText(usuario.getApellido());
            emailUsr.setText(usuario.getEmail());
            celularUsr.setText(usuario.getCelular());
            passwordUsr.setText(usuario.getContrasena());
            nacimientoUsr.setText(usuario.getFechaNacimiento() + "");
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        aliasUsr = new javax.swing.JTextField();
        nombreUsr = new javax.swing.JTextField();
        nacimientoUsr = new javax.swing.JFormattedTextField();
        apellidoUsr = new javax.swing.JTextField();
        emailUsr = new javax.swing.JTextField();
        celularUsr = new javax.swing.JTextField();
        passwordUsr = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        emailInfo = new javax.swing.JLabel();
        apellidoInfo = new javax.swing.JLabel();
        nombreInfo = new javax.swing.JLabel();
        aliasInfo = new javax.swing.JLabel();
        celularInfo = new javax.swing.JLabel();
        passwordInfo = new javax.swing.JLabel();
        fechaInfo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        UsrFormInfo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        aliasUsr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                aliasUsrFocusLost(evt);
            }
        });

        try {
            nacimientoUsr.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        emailUsr.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                emailUsrFocusLost(evt);
            }
        });

        jButton1.setText("Cancelar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton2MousePressed(evt);
            }
        });

        jLabel1.setText("Alias");

        jLabel2.setText("Nombre");

        jLabel3.setText("Apellido");

        jLabel4.setText("Email");

        jLabel5.setText("Celular");

        jLabel6.setText("Contraseña");

        jLabel7.setText("Fecha de Nacimiento (AAAA/MM/DD)");

        emailInfo.setForeground(new java.awt.Color(255, 0, 0));
        emailInfo.setText("Por favor ingrese un email valido");

        apellidoInfo.setForeground(new java.awt.Color(255, 0, 0));
        apellidoInfo.setText("Por favor ingrese sus apellidos");

        nombreInfo.setForeground(new java.awt.Color(255, 0, 0));
        nombreInfo.setText("Por favor ingrese su nombre");

        aliasInfo.setForeground(new java.awt.Color(255, 0, 0));
        aliasInfo.setText("Por favor ingrese un alias");

        celularInfo.setForeground(new java.awt.Color(255, 0, 0));
        celularInfo.setText("Por favor ingrese un numero celular");

        passwordInfo.setForeground(new java.awt.Color(255, 0, 0));
        passwordInfo.setText("Por favor ingrese una contraseña");

        fechaInfo.setForeground(new java.awt.Color(255, 0, 0));
        fechaInfo.setText("Por favor ingrese su fecha de nacimiento");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel8.setText("Usuario");

        UsrFormInfo.setForeground(new java.awt.Color(255, 0, 0));
        UsrFormInfo.setText("Por favor verifique los datos.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(passwordInfo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(celularInfo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(emailInfo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(apellidoInfo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(nombreInfo))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(aliasUsr)
                                .addComponent(nombreUsr)
                                .addComponent(apellidoUsr)
                                .addComponent(emailUsr)
                                .addComponent(celularUsr)
                                .addComponent(passwordUsr)
                                .addComponent(nacimientoUsr, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE))
                            .addComponent(fechaInfo)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(29, 29, 29)
                                .addComponent(aliasInfo))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel8))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(UsrFormInfo))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton2)
                                .addGap(30, 30, 30)
                                .addComponent(jButton1)))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(aliasInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(aliasUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nombreInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(apellidoInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apellidoUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(emailInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(celularInfo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(celularUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(passwordInfo))
                .addGap(2, 2, 2)
                .addComponent(passwordUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nacimientoUsr, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fechaInfo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(UsrFormInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emailUsrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_emailUsrFocusLost
        if (!(Pattern.matches("^[a-zA-Z0-9]+[@]{1}+[a-zA-Z0-9]+[.]{1}+[a-zA-Z0-9]+$", emailUsr.getText()))) {
            emailInfo.setVisible(true);
        } else {
            emailInfo.setVisible(false);
        }


    }//GEN-LAST:event_emailUsrFocusLost

    private void aliasUsrFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_aliasUsrFocusLost
        if ((aliasUsr.getText().length() < 3)) {
            aliasInfo.setVisible(true);
        } else {
            aliasInfo.setVisible(false);
        }
    }//GEN-LAST:event_aliasUsrFocusLost

    private void jButton2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MousePressed
        try {
            crear();

            dispose();
        } catch (Exception e) {

        }


    }//GEN-LAST:event_jButton2MousePressed
    void crear() throws ParseException {
        String bufDt = nacimientoUsr.getText();  //data from form
        DateFormat dF = new SimpleDateFormat("yyyy-MM-dd"); //data in form is in this format
        Date bbdt = (Date) dF.parse(bufDt);  // string data is converted into java util date     
        String ndt = dF.format(bbdt); // java util date is converted to compatible java sql date
        java.sql.Date sqlDate = java.sql.Date.valueOf(ndt);  // finally data from the form is convered to java sql. date for placing in database

        Usuario usr = new Usuario(aliasUsr.getText(), nombreUsr.getText(), apellidoUsr.getText(), emailUsr.getText(), celularUsr.getText(), passwordUsr.getText(), sqlDate);
        usuarioRepositorio.save(usr);

    }


    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MousePressed
        dispose();
    }//GEN-LAST:event_jButton1MousePressed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UsuarioForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UsuarioForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel UsrFormInfo;
    private javax.swing.JLabel aliasInfo;
    private javax.swing.JTextField aliasUsr;
    private javax.swing.JLabel apellidoInfo;
    private javax.swing.JTextField apellidoUsr;
    private javax.swing.JLabel celularInfo;
    private javax.swing.JTextField celularUsr;
    private javax.swing.JLabel emailInfo;
    private javax.swing.JTextField emailUsr;
    private javax.swing.JLabel fechaInfo;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JFormattedTextField nacimientoUsr;
    private javax.swing.JLabel nombreInfo;
    private javax.swing.JTextField nombreUsr;
    private javax.swing.JLabel passwordInfo;
    private javax.swing.JTextField passwordUsr;
    // End of variables declaration//GEN-END:variables
}
