/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package misiontic.reflix.vista;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author Danie
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    CardLayout cardLayout;
    public Home() {
        initComponents();
        cardLayout = (CardLayout)(pnlCards.getLayout());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlParent = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jSplitPane1 = new javax.swing.JSplitPane();
        sidepanel = new javax.swing.JPanel();
        btn_contenido = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ind_contenidos = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btn_peliculas = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ind_peliculas = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btn_series = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        ind_series = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        btn_usuarios = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        ind_usuarios = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        btn_directores = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        ind_directores = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pnlCards = new javax.swing.JPanel();
        pnlCard1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        pnlCard2 = new javax.swing.JPanel();
        pnlCard3 = new javax.swing.JPanel();
        pnlCard4 = new javax.swing.JPanel();
        pnlCard5 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        pnlParent.setBackground(new java.awt.Color(0, 0, 0));
        pnlParent.setForeground(new java.awt.Color(0, 0, 0));

        jPanel1.setBackground(new java.awt.Color(45, 45, 45));
        jPanel1.setForeground(new java.awt.Color(45, 45, 45));

        jLabel13.setBackground(new java.awt.Color(51, 51, 255));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("X");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel13MousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 1047, Short.MAX_VALUE)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jSplitPane1.setDividerSize(0);
        jSplitPane1.setPreferredSize(new java.awt.Dimension(450, 600));

        sidepanel.setBackground(new java.awt.Color(51, 51, 51));

        btn_contenido.setBackground(new java.awt.Color(51, 51, 51));
        btn_contenido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_contenidoMousePressed(evt);
            }
        });
        btn_contenido.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_contenido.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_contenidos.setBackground(new java.awt.Color(255, 51, 0));
        ind_contenidos.setOpaque(false);

        javax.swing.GroupLayout ind_contenidosLayout = new javax.swing.GroupLayout(ind_contenidos);
        ind_contenidos.setLayout(ind_contenidosLayout);
        ind_contenidosLayout.setHorizontalGroup(
            ind_contenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_contenidosLayout.setVerticalGroup(
            ind_contenidosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_contenido.add(ind_contenidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contenidos");
        btn_contenido.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 40));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("REDFLIX");

        btn_peliculas.setBackground(new java.awt.Color(51, 51, 51));
        btn_peliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_peliculasMousePressed(evt);
            }
        });
        btn_peliculas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_peliculas.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_peliculas.setBackground(new java.awt.Color(255, 51, 0));
        ind_peliculas.setOpaque(false);

        javax.swing.GroupLayout ind_peliculasLayout = new javax.swing.GroupLayout(ind_peliculas);
        ind_peliculas.setLayout(ind_peliculasLayout);
        ind_peliculasLayout.setHorizontalGroup(
            ind_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_peliculasLayout.setVerticalGroup(
            ind_peliculasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_peliculas.add(ind_peliculas, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Peliculas");
        btn_peliculas.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 40));

        btn_series.setBackground(new java.awt.Color(51, 51, 51));
        btn_series.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_seriesMousePressed(evt);
            }
        });
        btn_series.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_series.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_series.setBackground(new java.awt.Color(255, 51, 0));
        ind_series.setOpaque(false);

        javax.swing.GroupLayout ind_seriesLayout = new javax.swing.GroupLayout(ind_series);
        ind_series.setLayout(ind_seriesLayout);
        ind_seriesLayout.setHorizontalGroup(
            ind_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_seriesLayout.setVerticalGroup(
            ind_seriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_series.add(ind_series, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Series");
        btn_series.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, -1, 40));

        btn_usuarios.setBackground(new java.awt.Color(51, 51, 51));
        btn_usuarios.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_usuariosMousePressed(evt);
            }
        });
        btn_usuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_usuarios.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_usuarios.setBackground(new java.awt.Color(255, 51, 0));
        ind_usuarios.setOpaque(false);

        javax.swing.GroupLayout ind_usuariosLayout = new javax.swing.GroupLayout(ind_usuarios);
        ind_usuarios.setLayout(ind_usuariosLayout);
        ind_usuariosLayout.setHorizontalGroup(
            ind_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_usuariosLayout.setVerticalGroup(
            ind_usuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_usuarios.add(ind_usuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Usuarios");
        btn_usuarios.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, -1, 40));

        btn_directores.setBackground(new java.awt.Color(51, 51, 51));
        btn_directores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btn_directoresMousePressed(evt);
            }
        });
        btn_directores.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        btn_directores.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 0, 45, -1));

        ind_directores.setBackground(new java.awt.Color(255, 51, 0));
        ind_directores.setOpaque(false);

        javax.swing.GroupLayout ind_directoresLayout = new javax.swing.GroupLayout(ind_directores);
        ind_directores.setLayout(ind_directoresLayout);
        ind_directoresLayout.setHorizontalGroup(
            ind_directoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 5, Short.MAX_VALUE)
        );
        ind_directoresLayout.setVerticalGroup(
            ind_directoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 41, Short.MAX_VALUE)
        );

        btn_directores.add(ind_directores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 5, 41));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Directores");
        btn_directores.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, -1, 40));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 10)); // NOI18N
        jLabel12.setText("V1.0");

        javax.swing.GroupLayout sidepanelLayout = new javax.swing.GroupLayout(sidepanel);
        sidepanel.setLayout(sidepanelLayout);
        sidepanelLayout.setHorizontalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_contenido, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)
            .addComponent(btn_peliculas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_series, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_usuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_directores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addGap(42, 42, 42))
        );
        sidepanelLayout.setVerticalGroup(
            sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sidepanelLayout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addGroup(sidepanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addGap(92, 92, 92)
                .addComponent(btn_contenido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_peliculas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_series, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_usuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_directores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120))
        );

        jSplitPane1.setLeftComponent(sidepanel);

        pnlCards.setBackground(new java.awt.Color(204, 204, 204));
        pnlCards.setLayout(new java.awt.CardLayout());

        pnlCard1.setBackground(new java.awt.Color(255, 51, 102));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("jButton1");

        jButton2.setText("jButton2");

        jButton3.setText("jButton3");

        javax.swing.GroupLayout pnlCard1Layout = new javax.swing.GroupLayout(pnlCard1);
        pnlCard1.setLayout(pnlCard1Layout);
        pnlCard1Layout.setHorizontalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 753, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCard1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jButton1)
                        .addGap(103, 103, 103)
                        .addComponent(jButton2)
                        .addGap(113, 113, 113)
                        .addComponent(jButton3)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        pnlCard1Layout.setVerticalGroup(
            pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCard1Layout.createSequentialGroup()
                .addGap(156, 156, 156)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addGroup(pnlCard1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(65, Short.MAX_VALUE))
        );

        pnlCards.add(pnlCard1, "pnlCard1");

        pnlCard2.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlCard2Layout = new javax.swing.GroupLayout(pnlCard2);
        pnlCard2.setLayout(pnlCard2Layout);
        pnlCard2Layout.setHorizontalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        pnlCard2Layout.setVerticalGroup(
            pnlCard2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        pnlCards.add(pnlCard2, "pnlCard2");

        pnlCard3.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlCard3Layout = new javax.swing.GroupLayout(pnlCard3);
        pnlCard3.setLayout(pnlCard3Layout);
        pnlCard3Layout.setHorizontalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        pnlCard3Layout.setVerticalGroup(
            pnlCard3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        pnlCards.add(pnlCard3, "card5");

        pnlCard4.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlCard4Layout = new javax.swing.GroupLayout(pnlCard4);
        pnlCard4.setLayout(pnlCard4Layout);
        pnlCard4Layout.setHorizontalGroup(
            pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        pnlCard4Layout.setVerticalGroup(
            pnlCard4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        pnlCards.add(pnlCard4, "card4");

        pnlCard5.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlCard5Layout = new javax.swing.GroupLayout(pnlCard5);
        pnlCard5.setLayout(pnlCard5Layout);
        pnlCard5Layout.setHorizontalGroup(
            pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        pnlCard5Layout.setVerticalGroup(
            pnlCard5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );

        pnlCards.add(pnlCard5, "card3");

        jSplitPane1.setRightComponent(pnlCards);

        javax.swing.GroupLayout pnlParentLayout = new javax.swing.GroupLayout(pnlParent);
        pnlParent.setLayout(pnlParentLayout);
        pnlParentLayout.setHorizontalGroup(
            pnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlParentLayout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1088, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlParentLayout.setVerticalGroup(
            pnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlParentLayout.createSequentialGroup()
                .addGap(0, 48, Short.MAX_VALUE)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(pnlParentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlParentLayout.createSequentialGroup()
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 613, Short.MAX_VALUE)))
        );

        getContentPane().add(pnlParent, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_contenidoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_contenidoMousePressed
        setColor(btn_contenido);
        resetColor(btn_directores);
        resetColor(btn_peliculas);
        resetColor(btn_series);
        resetColor(btn_usuarios);
        ind_contenidos.setOpaque(true);
        ind_directores.setOpaque(false);
        ind_peliculas.setOpaque(false);
        ind_series.setOpaque(false);
        ind_usuarios.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard1");
        
    }//GEN-LAST:event_btn_contenidoMousePressed

    private void btn_peliculasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_peliculasMousePressed
        setColor(btn_peliculas);
        resetColor(btn_directores);
        resetColor(btn_contenido);
        resetColor(btn_series);
        resetColor(btn_usuarios);
        ind_peliculas.setOpaque(true);
        ind_contenidos.setOpaque(false);
        ind_directores.setOpaque(false);
        ind_series.setOpaque(false);
        ind_usuarios.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard2");
    }//GEN-LAST:event_btn_peliculasMousePressed

    private void btn_seriesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_seriesMousePressed
        setColor(btn_series);
        resetColor(btn_directores);
        resetColor(btn_contenido);
        resetColor(btn_peliculas);
        resetColor(btn_usuarios);
        ind_series.setOpaque(true);
        ind_contenidos.setOpaque(false);
        ind_directores.setOpaque(false);
        ind_peliculas.setOpaque(false);
        ind_usuarios.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard3");
    }//GEN-LAST:event_btn_seriesMousePressed

    private void btn_usuariosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_usuariosMousePressed
        setColor(btn_usuarios);
        resetColor(btn_directores);
        resetColor(btn_contenido);
        resetColor(btn_peliculas);
        resetColor(btn_series);
        ind_usuarios.setOpaque(true);
        ind_contenidos.setOpaque(false);
        ind_directores.setOpaque(false);
        ind_peliculas.setOpaque(false);
        ind_series.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard4");
    }//GEN-LAST:event_btn_usuariosMousePressed

    private void btn_directoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_directoresMousePressed
        setColor(btn_directores);
        resetColor(btn_usuarios);
        resetColor(btn_contenido);
        resetColor(btn_peliculas);
        resetColor(btn_series);
        ind_directores.setOpaque(true);
        ind_contenidos.setOpaque(false);
        ind_peliculas.setOpaque(false);
        ind_series.setOpaque(false);
        ind_usuarios.setOpaque(false);
        cardLayout.show(pnlCards, "pnlCard5");
    }//GEN-LAST:event_btn_directoresMousePressed

    private void jLabel13MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MousePressed
        System.exit(0);
    }//GEN-LAST:event_jLabel13MousePressed

    void setColor(JPanel panel){
        panel.setBackground(new Color(102,102,102));
    }
    void resetColor(JPanel panel){
        panel.setBackground(new Color(51,51,51));
    }
    
    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel btn_contenido;
    private javax.swing.JPanel btn_directores;
    private javax.swing.JPanel btn_peliculas;
    private javax.swing.JPanel btn_series;
    private javax.swing.JPanel btn_usuarios;
    private javax.swing.JPanel ind_contenidos;
    private javax.swing.JPanel ind_directores;
    private javax.swing.JPanel ind_peliculas;
    private javax.swing.JPanel ind_series;
    private javax.swing.JPanel ind_usuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JPanel pnlCard1;
    private javax.swing.JPanel pnlCard2;
    private javax.swing.JPanel pnlCard3;
    private javax.swing.JPanel pnlCard4;
    private javax.swing.JPanel pnlCard5;
    private javax.swing.JPanel pnlCards;
    private javax.swing.JPanel pnlParent;
    private javax.swing.JPanel sidepanel;
    // End of variables declaration//GEN-END:variables
}


